id:
  pattern: "^[0-9]+$"  # по умолчанию ожидаем только цифры

admin:
  approve_durations:
    - 0       # бессрочно
    - 2592000 # 30 дней
  enable_decline: true
  enable_ban: true

expiration:
  check_interval: 60
  warn_before_sec: 86400

session_timeout:
  seconds: 900
  send_message: false

renewal:
  warn_before_sec: 86400
  grace_after_expiry_sec: 86400
  user_plans:
    - id: trial_3d
      label:
        en: "Subscribe for trial period"
        ru: "Подписаться на пробный период"
      duration_sec: 259200
    - id: month_30
      label:
        en: "Buy 30-day subscription"
        ru: "Купить подписку на 30 дней"
      duration_sec: 2592000
    - id: lifetime
      label:
        en: "Buy lifetime subscription"
        ru: "Купить бессрочную подписку"
      duration_sec: 0
