start:
  template: start_user.txt
  action_button_text:
    en: "Get access"
    ru: "Получить доступ"
    # extend with more locales as needed
  enabled_image: true
  image:
    en: { path: assets/en/start.jpg }
    ru: { path: assets/ru/start.jpg }

messages:
  ask_id: ask_id.txt
  waiting: id_waiting.txt
  banned: id_banned.txt
  not_found: id_not_found.txt
  granted: access_granted.txt
  denied: access_denied.txt
  warning: expiry_warning.txt
  expired: expired.txt
  admin_request: admin_request.txt
  renewal_warning: renewal_warning.txt
  grace_warning: grace_warning.txt
  renewal_requested_admin: renewal_requested_admin.txt
  links_unavailable: links_unavailable.txt
  session_timeout: session_timeout.txt

admin_interface:
  lifetime_text:
    en: "lifetime"
    ru: "бессрочно"

  approve_template:
    en: "Approve for {period}"
    ru: "Подтвердить на {period}"
  decline_text:
    en: "Decline"
    ru: "Отклонить"
  ban_text:
    en: "Ban"
    ru: "Забанить"
  unban_text:
    en: "Unban"
    ru: "Разбанить"
  kick_text:
    en: "Kick"
    ru: "Кикнуть"
  remove_text:
    en: "Remove"
    ru: "Удалить"

language_prompt:
  enabled_image: true
  template: language_prompt.txt
  image:
    en: { path: assets/en/language.jpg }
    ru: { path: assets/ru/language.jpg }

start_language_prompt:
  enabled_image: true
  template: start_language_prompt.txt
  image:
    en: { path: assets/en/language.jpg }
    ru: { path: assets/ru/language.jpg }

ask_id_prompt:
  enabled_image: true
  template: ask_id.txt
  image:
    en: { path: assets/en/id_example.jpg }
    ru: { path: assets/ru/id_example.jpg }

invalid_id_prompt:
  enabled_image: true
  template: id_invalid.txt
  image:
    en: { path: assets/en/id_example.jpg }
    ru: { path: assets/ru/id_example.jpg }

post_join:
  enabled: true
  enabled_image: true
  template: post_join.txt
  image:
    en: { path: assets/en/final.jpg }
    ru: { path: assets/ru/final.jpg }

behavior:
  suppress_service_messages: true
