start:
  template: start_user.txt
  action_button_text: "Получить доступ"
  image: null

messages:
  ask_id: ask_id.txt
  waiting: id_waiting.txt
  banned: id_banned.txt
  not_found: id_not_found.txt
  granted: access_granted.txt
  denied: access_denied.txt
  warning: expiry_warning.txt
  expired: expired.txt
  admin_request: admin_request.txt

admin_interface:
  approve_template: "Разрешить на {period}"
  decline_text: "Отклонить"
  ban_text: "Забанить"
